### ISSUE TITLE
Speech Dispatcher interop?

### ISSUE THREAD

**Issue by vixalien** [project-spiel/libspiel#66]
It would be nice if libspiel could integrate or replace with current installs of speech dispatcher. I'm not familiar with either, but here are some (probably unfeasible) ideas:

- "Emulate" speech dispatcher. so that apps that currently expect speech dispatcher will find it, however with the found speech dispatcher actually being a frontend for libspiel
- Add libspiel as a speech dispatcher engine. This would forward all requests to libspiel, and would probably need to read user configuration from somewhere.

I'm just a desktop linux user, so feel free to close this issue if it doesn't align with the goal of the project. Thanks for the awesome work!!

**Comment by TheMuso** [comment]
I personally think it makes more sense to have a daemon that accepts speech-dispatcher client connections, and uses libspiel. Having libspiel use speech-dispatcher doesn't really make sense in my opinion.

**Comment by eeejay** [comment]
>     * "Emulate" speech dispatcher. so that apps that currently expect speech dispatcher will find it, however with the found speech dispatcher actually being a frontend for libspiel
> 

There are only a handful of "speaking" apps. A quick search for `speechd`/`speech-dispatcher` in flathub shows most of them. I think time could be better spent migrating those apps. Orca, speech dispatcher's biggest consumer already supports spiel.

Are there any specific apps you would like to see work with libspiel?

>     * Add libspiel as a speech dispatcher engine. This would forward all requests to libspiel, and would probably need to read user configuration from somewhere.

I think this task belongs in the speech dispatcher project and not here. I don't know if there is interest in this kind of work.

> 
> I'm just a desktop linux user, so feel free to close this issue if it doesn't align with the goal of the project. Thanks for the awesome work!!

:heart:

**Comment by vixalien** [comment]
I was actually thinking about Firefox and Chrome

**Comment by eeejay** [comment]
I already wrote a patch for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1909297

Chrome uses cloud google voices and not speech dispatcher.

WebKitGTK does not currently support synthesis, but when it will it will hopefully be via libspiel: https://bugs.webkit.org/show_bug.cgi?id=270742

I'll close this for now, but if there is more energy behind a compat layer we can open an issue in the right component. Thank you for filing!
