### ISSUE TITLE
Please allow to build against a system-installed version of libspeechprovider

### ISSUE THREAD

**Issue by clopez** [project-spiel/libspiel#68]
Currently is not possible to build and install libspeechprovider first, and then use that build of libspeechprovider from libspiel.

libspiel insists in cloning libspeechprovider as a subproject instead of using the previous one built and installed on the system

This makes packaging this software an issue on distros that have the policy of shipping each package independently.

**Comment by clopez** [comment]
For example, I was trying to package this for Yocto but I jumped into the problem that yocto passes to meson the option `--wrap-mode nodownload` so that makes the configure step fail with:

```
| Compiler for C supports arguments -Wunused: YES
| Compiler for C supports arguments -fno-strict-aliasing: YES
| Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES
| 
| ../git/meson.build:87:22: ERROR: Automatic wrap-based subproject downloading is disabled
| 
| A full log can be found at /home/clopez/webkit/webkit/WebKitBuild/CrossToolChains/rpi4-64bits-mesa/build/tmp/work/cortexa72-poky-linux/libspiel/1.0.1/build/meson-logs/meson-log.txt
| ERROR: meson failed
| WARNING: exit code 1 from a shell command.
```


I tried to package libspeechprovider and use it as system dependency but the meson system of libspiel is not ready to use it as an external dependency, because it tries to read from it a variable named `iface_xml` that I don't know how to provide otherwise.

**Comment by philn** [comment]
Thanks for reporting this issue, I also noticed it :(
I suspect the libspeechprovider shouldn't declared as a subproject, but as a dependency.

**Comment by philn** [comment]
cc @eeejay :)

**Comment by philn** [comment]
And the `iface_xml` var should be added to the speech-provider-1.0.pc I think?

**Comment by eeejay** [comment]
Should be fixed with f77d9af7da4ca925ba33e2a9016b48c09d0af1c1.

**Comment by philn** [comment]
I've built libspeechprovider separately with meson, then from its `meson devenv` shell I tried to build libspiel:

```
Run-time dependency speech-provider-1.0 found: YES 1.0.2                                                                                                                                                           
                                                                                                                                                                                                                   
meson.build:89:33: ERROR: Could not get pkg-config variable and no default provided for <PkgConfigDependency speech-provider-1.0: True ['>= 1.0.2']>
```

**Comment by philn** [comment]
`libspeechprovider/build/meson-private/speech-provider-1.0.pc` has the `iface_xml` variable, but not `speech-provider-1.0-uninstalled.pc`

**Comment by eeejay** [comment]
Sorry about that. Hopefully fixed in https://github.com/project-spiel/libspeechprovider/commit/b3ea281ce49a9bc74c273a57c7704d476ea68006
